services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_php
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
