services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: botdb
      MYSQL_USER: botuser
      MYSQL_PASSWORD: botpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: botuser
      PMA_PASSWORD: botpass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
